apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7.27
          imagePullPolicy: Always
          name: mysql
          args: 
            - "--lower_case_table_names=1"
            - "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
            - "--max_allowed_packet=512MB"
            - "--character-set-server=utf8"
            - "--collation-server=utf8_unicode_ci"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name:  mysqlrootpassword
                    key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                  secretKeyRef:
                    name:  mysqldatabase
                    key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                  secretKeyRef:
                    name:  mysqluser
                    key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name:  mysqlpassword
                    key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-clai

