apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volum
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data"
